### ISSUE TITLE
Compile current buffer: Compile error for classes

### ISSUE THREAD

**Issue by Hoempi** [vscode-abl/vscode-abl#165]
I have a file named `BBCAIDataCockpitSvc.cls`. When using "compile current buffer" I get a compilation error, which I do not get in the Progress Developer Studio.

The reason for this seems to be, that a temporary file is created, which does not end on `.cls`:

> Class statement may only be used in files with '.cls' extension. (12622)
> ** d:\proALPHA\proalpha-code\proalpha-de-9master\dev\dev\.builder\buffer\tmp20248398192700 Could not understand line 47. (196)

I found the [Issue 131](https://github.com/vscode-abl/vscode-abl/issues/131), but it is closed and the problem does not seem to be resolved yet. Also I do not spot the "check syntax" option mentionend in that issue. I would prefer to use "check syntax" anyway, am I missing something?

**Comment by gquerret** [comment]
This is fixed in the pre-release stream of the extension.

**Comment by Hoempi** [comment]
Great, thank you! I'll test tomorrow when I'm back at the desk.

**Comment by ccecvb** [comment]
Hi @gquerret,  
I tested compile current buffer on a class , but I still get error 12622

I switched to pre-release version and restarted the language server

![image](https://github.com/user-attachments/assets/3bc066f1-e9c2-4fb8-9296-94c49974f552)

* Workspace on linux
* Source relative path git/ccesmarttools/CceFramework/src/be/cce/ccetools/winkit/EmbeddedWindowFormSettings.cls
* Source relative to propath source entry be/cce/ccetools/winkit/EmbeddedWindowFormSettings.cls


```
  "buildPath": [
    {
      "path": "git/ccesmarttools/CceFramework",
      "type": "propath"
    },
    {
      "path": "git/ccesmarttools/CceFramework/src",
      "type": "source",
      "includes": "**/*.p,**/*.cls",
      "excludesFile": "excludes.lst"
    },
...

```

**Comment by Hoempi** [comment]
For me the error message regarding the .cls extension of the file is gone. Now I'm getting some other errors. But that needs further investigating on my part and has relation to this issue.

But as @ccecvb reported still facing the problem, I would leave this issue open.

**Comment by gquerret** [comment]
@ccecvb What do you see in `.builder/clientlogX.log` when you execute the action ?

**Comment by ccecvb** [comment]
.builder/clientlog0.log contains

```
[24/07/24@14:46:43.611+0200] P-2989042 T-2989042 1 4GL APPL           Compile buffer /home/cvb@CCE.local/workspaces/develop/.builder/buffer/tmp5974065559687859
[24/07/24@14:46:43.611+0200] P-2989042 T-2989042 1 4GL -- (Procedure: 'compileBuffer /home/cvb@CCE.local/workspaces/develop/.builder/ls/thread.p' Line:360) Class statement may only be used in files with '.cls' extension. (12622)
[24/07/24@14:46:43.611+0200] P-2989042 T-2989042 1 4GL -- (Procedure: 'compileBuffer /home/cvb@CCE.local/workspaces/develop/.builder/ls/thread.p' Line:360) ** /home/cvb@CCE.local/workspaces/develop/.builder/buffer/tmp5974065559687859 Could not understand line 13. (196)

``` 

I tried closing & re-opening the workspace, but now compile does nothing and I see the
```
[2024-07-24T14:54:25.318+0200] [ERROR] [develop] Builder is already started
```
from #163

**Comment by ccecvb** [comment]
@gquerret  After killing vscode

```
ps aux | grep node | grep userid | awk '{ print $2 }' | xargs kill
```

and restarting vscode. 
I can do a syntax check on class files

It still fails for interfaces

```
[24/07/24@16:30:26.412+0200] P-3204417 T-3204417 1 4GL APPL           Rename buffer to be.cce.ccetools.ui.WindowSettings.cls
[24/07/24@16:30:26.414+0200] P-3204417 T-3204417 1 4GL -- (Procedure: 'compileBuffer /home/cvb@CCE.local/workspaces/develop/.builder/ls/thread.p' Line:386) Could not find class or interface Progress.Windows.Form. (12886)
[24/07/24@16:30:26.414+0200] P-3204417 T-3204417 1 4GL -- (Procedure: 'compileBuffer /home/cvb@CCE.local/workspaces/develop/.builder/ls/thread.p' Line:386) TYPE-OF 'Progress.Windows.Form' not allowed. TYPE-OF target must be a user defined type. (14447)
[24/07/24@16:30:26.414+0200] P-3204417 T-3204417 1 4GL -- (Procedure: 'compileBuffer /home/cvb@CCE.local/workspaces/develop/.builder/ls/thread.p' Line:386) ** be.cce.ccetools.ui.WindowSettings.cls Could not understand line 100. (198)
[24/07/24@16:31:04.139+0200] P-3204417 T-3204417 1 4GL APPL           Compile buffer /home/cvb@CCE.local/workspaces/develop/.builder/buffer/tmp5980326087867386
[24/07/24@16:31:04.139+0200] P-3204417 T-3204417 1 4GL -- (Procedure: 'compileBuffer /home/cvb@CCE.local/workspaces/develop/.builder/ls/thread.p' Line:363) Interface statement may only be used in files with '.cls' extension. (12623)
[24/07/24@16:31:04.139+0200] P-3204417 T-3204417 1 4GL -- (Procedure: 'compileBuffer /home/cvb@CCE.local/workspaces/develop/.builder/ls/thread.p' Line:363) ** /home/cvb@CCE.local/workspaces/develop/.builder/buffer/tmp5980326087867386 Could not understand line 11. (196)

```

**Comment by gquerret** [comment]
> I tried closing & re-opening the workspace, but now compile does nothing and I see the
> ```
> [2024-07-24T14:54:25.318+0200] [ERROR] [develop] Builder is already started
> ```
> from #163

Anything specific in your config ? The LS creates a `.builder/builder.lock` with exclusive lock during startup (and writes PID in it). This is released when the LS dies. Restarting the LS should never trigger this message.

**Comment by gquerret** [comment]
> It still fails for interfaces 
> ```
> [24/07/24@16:30:26.412+0200] P-3204417 T-3204417 1 4GL APPL           Rename buffer to be.cce.ccetools.ui.WindowSettings.cls
> [24/07/24@16:30:26.414+0200] P-3204417 T-3204417 1 4GL -- (Procedure: 'compileBuffer /home/cvb@CCE.local/workspaces/develop/.builder/ls/thread.p' Line:386) Could not find class or interface Progress.Windows.Form. (12886)
> [24/07/24@16:30:26.414+0200] P-3204417 T-3204417 1 4GL -- (Procedure: 'compileBuffer /home/cvb@CCE.local/workspaces/develop/.builder/ls/thread.p' Line:386) TYPE-OF 'Progress.Windows.Form' not allowed. TYPE-OF target must be a user defined type. (14447)
> [24/07/24@16:30:26.414+0200] P-3204417 T-3204417 1 4GL -- (Procedure: 'compileBuffer /home/cvb@CCE.local/workspaces/develop/.builder/ls/thread.p' Line:386) ** be.cce.ccetools.ui.WindowSettings.cls Could not understand line 100. (198)
> [24/07/24@16:31:04.139+0200] P-3204417 T-3204417 1 4GL APPL           Compile buffer /home/cvb@CCE.local/workspaces/develop/.builder/buffer/tmp5980326087867386
> [24/07/24@16:31:04.139+0200] P-3204417 T-3204417 1 4GL -- (Procedure: 'compileBuffer /home/cvb@CCE.local/workspaces/develop/.builder/ls/thread.p' Line:363) Interface statement may only be used in files with '.cls' extension. (12623)
> [24/07/24@16:31:04.139+0200] P-3204417 T-3204417 1 4GL -- (Procedure: 'compileBuffer /home/cvb@CCE.local/workspaces/develop/.builder/ls/thread.p' Line:363) ** /home/cvb@CCE.local/workspaces/develop/.builder/buffer/tmp5980326087867386 Could not understand line 11. (196)
> ```

Will be fixed for interfaces (and enums). The LS has to rename the temp file so that it matches the class name, and then recompile the new file. Done by catching a specific message number, but the number is different for classes, interfaces and enums. FWIW even Progress doesn't have a better solution, as the same thing is done by the procedure editor.

**Comment by gquerret** [comment]
Fixed in 1.9.17 (released earlier this afternoon)
