### ISSUE TITLE
Allow comments in openedge-project.json

### ISSUE THREAD

**Issue by gquerret** [vscode-abl/vscode-abl#3]
That was removed in the early stages of the migration (for unclear reasons).

**Comment by mikefechner** [comment]
Which style of comments are supported?

**Comment by gquerret** [comment]
It looks like `//` and `/* */` comments are supported by both Node and Java.

**Comment by stefandrissen** [comment]
I suggest updating the openedge-project.json on the readme.md to use comments that are automatically recognized as such when selecting language mode jsonc in vscode.

**Comment by gquerret** [comment]
> I suggest updating the openedge-project.json on the readme.md to use comments that are automatically recognized as such when selecting language mode jsonc in vscode.

Done ! Much more readable...

**Comment by stefandrissen** [comment]
I'm not sure where it's coming from, but the extension page shown in vscode is still showing the old version:
![image](https://user-images.githubusercontent.com/5297464/175482833-41c2c2a6-b79e-4433-97a5-20a6661850ff.png)

**Comment by stefandrissen** [comment]
The readme.md example is also still invalid json due to a missing comma:

      { "type": "source", "path": "src/dev", "includes": "foo/**,bar/**", "excludes": "foo/something/**" }
      { "type": "propath", "path": "${DLC}/tty/netlib/OpenEdge.net.pl" }

**Comment by gquerret** [comment]
> I'm not sure where it's coming from, but the extension page shown in vscode is still showing the old versio

The extension shows the file which in included in the vsix file, not the one on the website.

> The readme.md example is also still invalid json due to a missing comma

Also fixed
